---
# This playbook install the application.
- name: Copy application credentials
  become_user: "{{ kryten.user }}"
  template:
    src: .netrc
    dest: "~/.netrc"
  tags:
    - kryten
    - worksheet
    - delivery
- name: Copy pypi client side config
  become_user: "{{ kryten.user }}"
  template:
    src: .pypirc
    dest: "~/.pypirc"
  tags:
    - kryten
    - worksheet
    - delivery
- name: Copy pip client side config
  become_user: "{{ kryten.user }}"
  template:
    src: pip.conf
    dest: "~/.pip/pip.conf"
  tags:
    - kryten
    - worksheet
    - delivery
- include: upstart.yml
- include: configuration.yml
- include: site.yml
- include: reload.yml