---
# This playbook deploys the whole application stack in this site.
- name: First steps
  hosts: all
  remote_user: lordoftheflies
  become: yes
  roles:
    - postgresql
  tags:
    - kryten
    - install
- name: Install or full update
  hosts: all
  remote_user: lordoftheflies
  become: yes
  roles:
    - site
  tags:
    - kryten
    - integration