---
# This playbook deploys the whole application stack in this site.
- name: Setup database
  hosts: all
  remote_user: lordoftheflies
  become: yes
  roles:
    - database
  tags:
    - kryten
    - database